# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions

alias ls="ls --color=auto --ignore='*.pyc'"

eval `dircolors $HOME/.dir_colors`

[[ -s $HOME/.pythonbrew/etc/bashrc ]] && source $HOME/.pythonbrew/etc/bashrc

source ~/.git-completion.bash
