#! /bin/bash
# Set this script to run as an autostart application

wmctrl -n3

firefox &
#wait
terminal --fullscreen --command="screen -S dylan" &
#wait

wmctrl -r firefox -t 0
wmctrl -r terminal -t 1
