- name: copy files
  copy: src=google-chrome.sources
        dest=/etc/apt/sources.list.d/google-chrome.sources
        mode='0644'

- name: install google-chrome
  apt:
    state: latest
    update_cache: yes
    name:
      - fonts-liberation
      - libu2f-udev
      - google-chrome-stable

- name: remove google-chrome.list file
  file: path={{ item }} state=absent
  with_items:
    - /etc/apt/sources.list.d/google-chrome.list
    - /etc/apt/trusted.gpg.d/google-chrome.gpg
