
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '+\xa6\xfc\x1e\r O\xa3Z\xc3\xe0\x9c\xeb\xf6Q\xf1'
    
_lr_action_items = {'STRING':([0,1,2,3,11,12,13,14,21,22,23,24,25,26,28,29,31,33,37,38,],[2,2,7,2,13,14,15,16,-9,27,-8,-4,30,-5,-7,-6,-11,-13,-10,-12,]),'NEWLINE':([0,1,3,17,18,21,23,24,26,27,28,29,30,31,33,35,36,37,38,],[3,3,3,19,20,-9,-8,-4,-5,31,-7,-6,33,-11,-13,37,38,-10,-12,]),'ASTERISK':([19,20,21,23,24,26,28,29,31,33,37,38,],[22,22,-9,-8,22,22,-7,-6,-11,-13,-10,-12,]),'EQUALS':([27,30,],[32,34,]),'AMOUNT':([8,10,32,34,],[11,12,35,36,]),'COLON':([2,7,],[8,10,]),'DATE':([15,16,],[17,18,]),'X':([19,20,21,23,24,26,28,29,31,33,37,38,],[25,25,-9,-8,25,25,-7,-6,-11,-13,-10,-12,]),'$end':([0,1,3,4,5,6,9,21,23,24,26,28,29,31,33,37,38,],[-14,-14,-14,0,-3,-1,-2,-9,-8,-4,-5,-7,-6,-11,-13,-10,-12,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'name_x':([19,20,24,26,],[21,21,28,28,]),'bill':([0,1,3,],[1,1,1,]),'name_asterisk':([19,20,24,26,],[23,23,29,29,]),'names':([19,20,],[24,26,]),'bills':([0,1,3,],[4,6,9,]),'empty':([0,1,3,],[5,5,5,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> bills","S'",1,None,None,None),
  ('bills -> bill bills','bills',2,'p_bills','/home/dylan/workspace/utils/bills/parser/bills_yacc.py',16),
  ('bills -> NEWLINE bills','bills',2,'p_bills','/home/dylan/workspace/utils/bills/parser/bills_yacc.py',17),
  ('bills -> empty','bills',1,'p_bills','/home/dylan/workspace/utils/bills/parser/bills_yacc.py',18),
  ('bill -> STRING COLON AMOUNT STRING STRING DATE NEWLINE names','bill',8,'p_bill','/home/dylan/workspace/utils/bills/parser/bills_yacc.py',28),
  ('bill -> STRING STRING COLON AMOUNT STRING STRING DATE NEWLINE names','bill',9,'p_bill','/home/dylan/workspace/utils/bills/parser/bills_yacc.py',29),
  ('names -> names name_asterisk','names',2,'p_names','/home/dylan/workspace/utils/bills/parser/bills_yacc.py',46),
  ('names -> names name_x','names',2,'p_names','/home/dylan/workspace/utils/bills/parser/bills_yacc.py',47),
  ('names -> name_asterisk','names',1,'p_names','/home/dylan/workspace/utils/bills/parser/bills_yacc.py',48),
  ('names -> name_x','names',1,'p_names','/home/dylan/workspace/utils/bills/parser/bills_yacc.py',49),
  ('name_asterisk -> ASTERISK STRING EQUALS AMOUNT NEWLINE','name_asterisk',5,'p_name_asterisk','/home/dylan/workspace/utils/bills/parser/bills_yacc.py',56),
  ('name_asterisk -> ASTERISK STRING NEWLINE','name_asterisk',3,'p_name_asterisk','/home/dylan/workspace/utils/bills/parser/bills_yacc.py',57),
  ('name_x -> X STRING EQUALS AMOUNT NEWLINE','name_x',5,'p_name_x','/home/dylan/workspace/utils/bills/parser/bills_yacc.py',64),
  ('name_x -> X STRING NEWLINE','name_x',3,'p_name_x','/home/dylan/workspace/utils/bills/parser/bills_yacc.py',65),
  ('empty -> <empty>','empty',0,'p_empty','/home/dylan/workspace/utils/bills/parser/bills_yacc.py',72),
]
