- name: install packages
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - firefox
    - git
    - meld
    - mercurial
    - mercurial-keyring
    - python-pip
    - silversearcher-ag
    - tmux
    - tree
    - vim-gtk

- name: install pip packages
  pip: name={{ item }} state=latest
  with_items:
    - isort
    - tox
