- name: import the NodeSource GPG key into apt
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: add NodeSource deb repository
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_6.x {{ ansible_distribution_release }} main'
    state: present
    mode: 644

- name: add NodeSource deb-src repository
  apt_repository:
    repo: 'deb-src https://deb.nodesource.com/node_6.x {{ ansible_distribution_release }} main'
    state: present
    mode: 644

- name: install packages
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - curl
    - chromium-browser
    - default-jdk
    - git
    - hfsprogs
    - libdvd-pkg
    - meld
    - mosh
    - nodejs
    - python3
    - python3-dev
    - python3-pip
    - python3-venv
    - redshift
    - s3cmd
    - silversearcher-ag
    - texlive-latex-recommended
    - texlive-fonts-recommended
    - tmux
    - tree
    - vim
    - visualvm
    - xclip

- name: configure libdvd-pkg (for watching encrypted dvds)
  dpkg_reconfigure: 
    pkg: libdvd-pkg
    answers:
      libdvd-pkg/build: "yes"
      libdvd-pkg/post-invoke_hook-remove: "no"

- name: fzf | clone repo
  git: repo=https://github.com/junegunn/fzf.git dest={{ ansible_env.HOME }}/.fzf depth=1

- name: fzf | install
  command: '{{ ansible_env.HOME }}/.fzf/install' 
  args:
    creates: '{{ ansible_env.HOME }}/.fzf/bin/fzf'

- name: fzf | link into home bin
  file: src={{ ansible_env.HOME }}/.fzf/bin/{{ item }} dest={{ ansible_env.HOME }}/.local/bin/{{ item }} state=link
  with_items:
    - fzf
    - fzf-tmux

- name: install leiningen
  command: bash -c "cd /usr/local/bin && curl -fsSLo lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein && chmod 755 lein"
           creates=/usr/local/bin/lein

- name: install boot
  command: bash -c "cd /usr/local/bin && curl -fsSLo boot https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh && chmod 755 boot"
           creates=/usr/local/bin/boot
