- name: import the google talk plugin key
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present

- name: add google talk plugin repository
  apt_repository:
    repo: 'deb http://dl.google.com/linux/talkplugin/deb/ stable main'
    state: present
    mode: 644

- name: install packages
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - default-jdk
    - firefox
    - git
    - google-talkplugin
    - hfsprogs
    - libdvd-pkg
    - meld
    - mosh
    - python
    - python-dev
    - python-pip
    - s3cmd
    - silversearcher-ag
    - texlive-latex-recommended
    - texlive-fonts-recommended
    - tmux
    - tree
    - vim-gtk-py2
    - visualvm
    - xclip

- name: configure libdvd-pkg (for watching encrypted dvds)
  dpkg_reconfigure: 
    pkg: libdvd-pkg
    answers:
      libdvd-pkg/build: "yes"
      libdvd-pkg/post-invoke_hook-remove: "no"

- name: use vim compiled for python2
  alternatives: name=vim path=/usr/bin/vim.gtk-py2

- name: install pip packages
  pip: name={{ item }} state=latest
  with_items:
    - jupyter
    - isort
    - pip

- name: fzf | clone repo
  git: repo=https://github.com/junegunn/fzf.git dest={{ ansible_env.HOME }}/.fzf depth=1

- name: fzf | install
  command: '{{ ansible_env.HOME }}/.fzf/install' 
  args:
    creates: '{{ ansible_env.HOME }}/.fzf/bin/fzf'

- name: fzf | link into home bin
  file: src={{ ansible_env.HOME }}/.fzf/bin/{{ item }} dest={{ ansible_env.HOME }}/bin/{{ item }} state=link
  with_items:
    - fzf
    - fzf-tmux

- name: install leiningen
  command: bash -c "cd /usr/local/bin && curl -fsSLo lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein && chmod 755 lein"
           creates=/usr/local/bin/lein

- name: install boot
  command: bash -c "cd /usr/local/bin && curl -fsSLo boot https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh && chmod 755 boot"
           creates=/usr/local/bin/boot
