- name: import the NodeSource GPG key into apt
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: add NodeSource deb repository
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_4.x {{ ansible_distribution_release }} main'
    state: present

- name: add NodeSource deb-src repository
  apt_repository:
    repo: 'deb-src https://deb.nodesource.com/node_4.x {{ ansible_distribution_release }} main'
    state: present

- name: install packages
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - aptitude
    - default-jdk
    - firefox
    - git
    - libxml2-utils
    - meld
    - mercurial
    - mercurial-keyring
    - mosh
    - nodejs
    - python
    - python-dev
    - python-pip
    - silversearcher-ag
    - tmux
    - tree
    - vim-gtk-py2
    - xclip

- name: install firefox add-ons
  firefox_addon:
    url: '{{ item }}'
    state: present
  with_items:
    - https://addons.mozilla.org/en-US/firefox/addon/vimperator/
    - https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/
    - https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/
    - https://addons.mozilla.org/en-US/firefox/addon/session-manager/
    - https://addons.mozilla.org/en-US/firefox/addon/privacy-badger-firefox/
    - https://addons.mozilla.org/en-US/firefox/addon/lastpass-password-manager/
    # doesn't work with the firefox_addon role :(
    #- https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/

- name: use vim compiled for python2
  alternatives: name=vim path=/usr/bin/vim.gtk-py2

- name: install pip packages
  pip: name={{ item }} state=latest
  with_items:
    - flake8
    - ipython
    - isort
    - mkdocs
    - RBTools
    - s3cmd
    - virtualenv

- name: install npm packages
  npm: name={{ item }} state=latest global=yes
  with_items:
    - eslint

- name: fzf | clone repo
  git: repo=https://github.com/junegunn/fzf.git dest={{ ansible_env.HOME }}/.fzf depth=1

- name: fzf | install
  command: '{{ ansible_env.HOME }}/.fzf/install' 
  args:
    creates: '{{ ansible_env.HOME }}/.fzf/bin/fzf'

- name: fzf | link into home bin
  file: src={{ ansible_env.HOME }}/.fzf/bin/{{ item }} dest={{ ansible_env.HOME }}/bin/{{ item }} state=link
  with_items:
    - fzf
    - fzf-tmux

- name: install leiningen
  command: bash -c "cd /usr/local/bin && curl -fsSLo lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein && chmod 755 lein"
           creates=/usr/local/bin/lein
