- name: install packages
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - firefox
    - git
    - meld
    - mercurial
    - mercurial-keyring
    - python-pip
    - silversearcher-ag
    - vim-gtk
    - tmux
