- name: install packages
  apt:
    state: latest
    update_cache: yes
    name:
      - awscli
      - bluez
      - bc
      - curl
      - default-jre
      - eog
      - firefox-esr
      - fonts-symbola
      - fzf
      - git
      - gnome-keyring
      - gnumeric
      - iwd
      - kitty
      - libnotify-bin
      - libspa-0.2-bluetooth
      - ntfs-3g
      - mpv
      - parallel
      - pavucontrol
      - pipx
      - python3
      - python3-dev
      - python3-pip
      - python3-venv
      - rclone
      - ripgrep
      - rlwrap
      - sudo
      - texlive-fonts-extra
      - texlive-fonts-recommended
      - texlive-latex-extra
      - texlive-latex-recommended
      - tree
      - universal-ctags
      - watchman

- name: add me to sudo group
  ansible.builtin.user:
    name: '{{ ansible_env.USER }}'
    groups: sudo
    append: yes

- name: configure systemd to autostart iwd
  systemd:
    name: iwd.service
    enabled: yes
    state: started

- name: install tridactyl native messenger
  become: yes
  become_user: '{{ ansible_env.USER }}'
  shell: curl -fsSl https://raw.githubusercontent.com/tridactyl/tridactyl/master/native/install.sh | bash
  args:
    creates: '{{ ansible_env.HOME }}/.mozilla/native-messaging-hosts/tridactyl.json'

- name: install pipx packages
  become: yes
  become_user: '{{ ansible_env.USER }}'
  command: pipx install {{ item }}
  args:
    creates: '{{ ansible_env.HOME }}/.local/pipx/venvs/{{ item }}'
  with_items:
    - httpx[cli]
    - poetry
    - tzupdate

- name: install Terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
    remote_src: yes
    dest: /usr/local/bin
    mode: 0555
    creates: /usr/local/bin/terraform

- name: install jmespath
  get_url:
    url: https://github.com/jmespath/jp/releases/download/0.2.1/jp-linux-amd64
    dest: /usr/local/bin/jp
    mode: 0555
