- name: install packages
  apt:
    state: latest
    update_cache: yes
    name:
      - awscli
      - bc
      - curl
      - default-jre
      - eog
      - firefox-esr
      - fonts-symbola
      - git
      - gnome-keyring
      - gnumeric
      - iwd
      - kitty
      - libnotify-bin
      - ntfs-3g
      - mpv
      # For Duke VPN
      - openvpn
      - openconnect
      # /For Duke VPN
      - parallel
      - pavucontrol
      - python3
      - python3-dev
      - python3-pip
      - python3-venv
      - rclone
      - rlwrap
      - silversearcher-ag
      - sudo
      - texlive-fonts-extra
      - texlive-fonts-recommended
      - texlive-latex-extra
      - texlive-latex-recommended
      - tree
      - universal-ctags

- name: add me to sudo group
  ansible.builtin.user:
    name: '{{ ansible_env.USER }}'
    groups: sudo
    append: yes

- name: install keybase
  # I had to manually install by removing the libappindicator1 dependency.
  # https://github.com/keybase/client/issues/24413
  apt:
    deb: https://prerelease.keybase.io/keybase_amd64.deb

- name: install tridactyl native messenger
  become: yes
  become_user: '{{ ansible_env.USER }}'
  shell: curl -fsSl https://raw.githubusercontent.com/tridactyl/tridactyl/master/native/install.sh | bash
  args:
    creates: '{{ ansible_env.HOME }}/.mozilla/native-messaging-hosts/tridactyl.json'
    warn: false

- name: install vpn-slice
  pip:
    state: latest
    name: https://github.com/dlenski/vpn-slice/archive/master.zip

- name: install pip packages
  become: yes
  become_user: '{{ ansible_env.USER }}'
  pip:
    state: latest
    executable: pip3
    extra_args: --user
    name:
    - pipx

- name: install pipx packages
  become: yes
  become_user: '{{ ansible_env.USER }}'
  command: pipx install {{ item }}
  args:
    creates: '{{ ansible_env.HOME }}/.local/pipx/venvs/{{ item }}'
  with_items:
    - httpx[cli]
    - poetry
    - tzupdate

- name: install Terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
    remote_src: yes
    dest: /usr/local/bin
    mode: 0555
    creates: /usr/local/bin/terraform

- name: install jmespath
  get_url:
    url: https://github.com/jmespath/jp/releases/download/0.2.1/jp-linux-amd64
    dest: /usr/local/bin/jp
    mode: 0555

- name: install obsidian
  become: yes
  become_user: '{{ ansible_env.USER }}'
  get_url:
    url: https://github.com/obsidianmd/obsidian-releases/releases/download/v0.15.9/Obsidian-0.15.9.AppImage
    dest: '{{ ansible_env.HOME }}/.local/bin/obsidian'
    mode: 0755
