- name: ensures directories exist
  file: path={{ ansible_env.HOME }}/{{ item }} state=directory
  with_items:
    - .ssh/
    - bin/
    - .config/autostart/

- name: copy files
  copy: src={{ item.src }}
        dest={{ ansible_env.HOME }}/{{ item.dest }}
        owner={{ ansible_env.USER }}
  with_items:
    - { src: 'bash_profile', dest: '.bash_profile'}
    - { src: 'bashrc', dest: '.bashrc'}
    - { src: 'dircolors-dark', dest: '.dircolors'}
    - { src: 'gitconfig', dest: '.gitconfig'}
    - { src: 'hgrc', dest: '.hgrc'}
    - { src: 'ssh-config', dest: '.ssh/config'}
    - { src: 'pentadactylrc', dest: '.pentadactylrc'}

- name: copy energysavvy files
  copy: src={{ item.src }}
        dest={{ ansible_env.HOME }}/{{ item.dest }}
        owner={{ ansible_env.USER }}
        mode=0755
  with_items:
    - { src: 'es_bashrc', dest: '.es_bashrc'}
    - { src: 'es_hgrc', dest: '.hgrc'}
    - { src: 'generate_tags.sh', dest: 'bin/generate_tags.sh'}
    - { src: 'update_repos.sh', dest: 'bin/update_repos.sh'}
    - { src: 'set_brightness.py', dest: 'bin/set_brightness.py'}
  tags:
    - energysavvy

- name: set up es_bashrc
  lineinfile: dest={{ ansible_env.HOME }}/.bashrc line='source ~/.es_bashrc'
  tags:
    - energysavvy

- name: copy more energysavvy files
  template: src={{ item.src }}
            dest={{ ansible_env.HOME }}/{{ item.dest }}
            owner={{ ansible_env.USER }}
            mode=0755
  with_items:
    - { src: 'startup.j2', dest: 'bin/startup'}
    - { src: 'startup.desktop.j2', dest: '.config/autostart/startup.desktop'}
  tags:
    - energysavvy
