- name: ensures directories exist
  file: path={{ ansible_env.HOME }}/{{ item }} state=directory
  with_items:
    - .aws/
    - .boot/
    - .config/kitty
    - .config/tridactyl
    - .jupyter/
    - .lein/
    - .local/bin/
    - .ssh/

- name: copy files
  copy: src={{ item.src }}
        dest={{ ansible_env.HOME }}/{{ item.dest }}
        owner={{ ansible_env.USER }}
        mode={{ item.mode | default('0644') }}
  with_items:
    - {src: 'aider-conf', dest: '.aider.conf.yml'}
    - {src: 'aws-config', dest: '.aws/config'}
    - {src: 'bashrc', dest: '.bashrc'}
    - {src: 'gdocs-edit', dest: '.local/bin/gdocs-edit', mode: '0744'}
    - {src: 'google-chrome', dest: '.local/bin/google-chrome', mode: '0744'}
    - {src: 'gitconfig', dest: '.gitconfig'}
    - {src: 'gitignore', dest: '.gitignore'}
    - {src: 'inputrc', dest: '.inputrc'}
    - {src: 'jupyter_console_config.py', dest: '.jupyter/jupyter_console_config.py'}
    - {src: 'kitty.conf', dest: '.config/kitty/kitty.conf'}
    - {src: 'profile', dest: '.profile'}
    - {src: 'profile.boot', dest: '.boot/profile.boot'}
    - {src: 'profiles.clj', dest: '.lein/profiles.clj'}
    - {src: 'ssh-config', dest: '.ssh/config'}
    - {src: 'tridactylrc', dest: '.config/tridactyl/tridactylrc'}
