- name: ensures directories exist
  file: path={{ ansible_env.HOME }}/{{ item }} state=directory
  with_items:
    - .ssh/
    - bin/
    - .config/
    - .lein/
    - .boot/

- name: copy files
  copy: src={{ item.src }}
        dest={{ ansible_env.HOME }}/{{ item.dest }}
        owner={{ ansible_env.USER }}
        mode={{ item.mode | default('0644') }}
  with_items:
    - {src: 'bash_profile', dest: '.bash_profile'}
    - {src: 'bashrc', dest: '.bashrc'}
    - {src: 'dircolors-dark', dest: '.dircolors'}
    - {src: 'gitconfig', dest: '.gitconfig'}
    - {src: 'hgrc', dest: '.hgrc'}
    - {src: 'hgignore', dest: '.hgignore'}
    - {src: 'ssh-config', dest: '.ssh/config'}
    - {src: 'vimperatorrc', dest: '.vimperatorrc'}
    - {src: 'contains.py', dest: 'bin/contains.py'}
    - {src: 'tmux.conf', dest: '.tmux.conf'}
    - {src: 'local-eslint', dest: 'bin/local-eslint', mode: '0744'}
    - {src: 'flake8', dest: '.config/flake8'}
    - {src: 'profiles.clj', dest: '.lein/profiles.clj'}
    - {src: 'profile.boot', dest: '.boot/profile.boot'}
