- name: ensures directories exist
  file: path={{ ansible_env.HOME }}/{{ item }} state=directory
  with_items:
    - .aws/
    - .config/kitty
    - .config/tridactyl
    - .jupyter/
    - .local/bin/
    - .ssh/

- name: copy files
  copy: src={{ item.src }}
        dest={{ ansible_env.HOME }}/{{ item.dest }}
        owner={{ ansible_env.USER }}
        mode={{ item.mode | default('0644') }}
  with_items:
    - {src: 'aider-conf.yml', dest: '.aider.conf.yml'}
    - {src: 'aws-config', dest: '.aws/config'}
    - {src: 'bashrc', dest: '.bashrc'}
    - {src: 'doc-ansible', dest: '.local/bin/doc-ansible', mode: '0744'}
    - {src: 'doc-css', dest: '.local/bin/doc-css', mode: '0744'}
    - {src: 'doc-html', dest: '.local/bin/doc-html', mode: '0744'}
    - {src: 'doc-swayconfig', dest: '.local/bin/doc-swayconfig', mode: '0744'}
    - {src: 'gdocs-edit', dest: '.local/bin/gdocs-edit', mode: '0744'}
    - {src: 'google-chrome', dest: '.local/bin/google-chrome', mode: '0744'}
    - {src: 'gitconfig', dest: '.gitconfig'}
    - {src: 'gitignore', dest: '.gitignore'}
    - {src: 'inputrc', dest: '.inputrc'}
    - {src: 'jupyter_console_config.py', dest: '.jupyter/jupyter_console_config.py'}
    - {src: 'kitty/kitty.conf', dest: '.config/kitty/kitty.conf'}
    - {src: 'kitty/solarized-dark.conf', dest: '.config/kitty/solarized-dark.conf'}
    - {src: 'kitty/solarized-light.conf', dest: '.config/kitty/solarized-light.conf'}
    - {src: 'mimeapps.list', dest: '.config/mimeapps.list'}
    - {src: 'profile', dest: '.profile'}
    - {src: 'ssh-config', dest: '.ssh/config'}
    - {src: 'tridactylrc', dest: '.config/tridactyl/tridactylrc'}
