- name: install clojure
  shell: curl -L https://github.com/clojure/brew-install/releases/download/1.12.0.1488/linux-install.sh | bash
  args:
    creates: /usr/local/bin/clojure

- name: install clj-kondo
  unarchive:
    src: https://github.com/borkdude/clj-kondo/releases/download/v2024.11.14/clj-kondo-2024.11.14-linux-amd64.zip
    remote_src: yes
    dest: /usr/local/bin
    mode: 055
    creates: /usr/local/bin/clj-kondo

- name: install babashka
  unarchive:
    src: https://github.com/babashka/babashka/releases/download/v1.12.196/babashka-1.12.196-linux-amd64-static.tar.gz
    remote_src: yes
    dest: /usr/local/bin
    mode: 055
    creates: /usr/local/bin/bb
