- name: install clojure
  shell: curl https://download.clojure.org/install/linux-install-1.10.1.507.sh | bash
  args:
    creates: /usr/local/bin/clojure

- name: install leiningen
  command: bash -c "cd /usr/local/bin && curl -fsSLo lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein && chmod 755 lein"
           creates=/usr/local/bin/lein

- name: install boot
  command: bash -c "cd /usr/local/bin && curl -fsSLo boot https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh && chmod 755 boot"
           creates=/usr/local/bin/boot

- name: install clj-kondo
  unarchive:
    src: https://github.com/borkdude/clj-kondo/releases/download/v2020.02.15/clj-kondo-2020.02.15-linux-amd64.zip
    remote_src: yes
    dest: /usr/local/bin
    mode: 055
    creates: /usr/local/bin/clj-kondo


