- name: install default-jdk
  apt:
    state: latest
    update_cache: yes
    name:
      - default-jdk

- name: install android-studio
  ansible.builtin.unarchive:
    src: https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2021.1.1.22/android-studio-2021.1.1.22-linux.tar.gz
    remote_src: yes
    dest: /opt/
    mode: 0777
    creates: /opt/android-studio

- name: create android-studio script
  copy: src=android-studio
        dest={{ ansible_env.HOME }}/.local/bin/android-studio
        owner={{ ansible_env.USER }}
        mode=0744
