- name: install kubectl
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.20.1/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: 0755

- name: install kubeseal
  get_url:
    url: https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.13.1/kubeseal-linux-amd64
    dest: /usr/local/bin/kubeseal
    mode: 0755

- name: install k9s
  unarchive:
    src: https://github.com/derailed/k9s/releases/download/v0.24.2/k9s_Linux_x86_64.tar.gz
    remote_src: yes
    dest: /usr/local/bin
    exclude:
      - LICENSE
      - README.md
    mode: 0755
    creates: /usr/local/bin/k9s

- name: install kustomize
  unarchive:
    src: https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv3.8.10/kustomize_v3.8.10_linux_amd64.tar.gz
    remote_src: yes
    dest: /usr/local/bin
    creates: /usr/local/bin/kustomize

- name: install helm
  unarchive:
    src: https://get.helm.sh/helm-v3.5.3-linux-amd64.tar.gz
    remote_src: yes
    dest: /usr/local/bin
    exclude:
      - LICENSE
      - README.md
    creates: /usr/local/bin/helm
