# bash_profile runs for login shells, i.e. when you log in

# if the machine doesn't have a graphical keychain tool then uncomment this
# to automatically set up ssh-agent and add the user's key
#SSH_ENV="$HOME/.ssh/environment"
#
#function start_agent {
#     echo "Initialising new SSH agent..."
#     /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
#     echo succeeded
#     chmod 600 "${SSH_ENV}"
#     . "${SSH_ENV}" > /dev/null
#     /usr/bin/ssh-add;
#}
#
## Source SSH settings, if applicable
#
#if [ -f "${SSH_ENV}" ]; then
#     . "${SSH_ENV}" > /dev/null
#     #ps ${SSH_AGENT_PID} doesn't work under cywgin
#     ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
#         start_agent;
#     }
#else
#     start_agent;
#fi

if [ -x /usr/bin/setxkbmap ]; then
    setxkbmap -option ctrl:swapcaps
fi

source ~/.bashrc
