# Aliases
alias ls="ls --color=auto --ignore='*.pyc'"
#
# Set correct term for tmux so solarized theme works in vim
alias tmux="TERM=screen-256color-bce tmux"

# Set up dircolors to use solarized colors
if [ -x /usr/bin/dircolors ]; then
  test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
fi

# Set editors
export VISUAL=vim
export EDITOR=vim

# vi mode
set -o vi


# if the machine doesn't have a graphical keychain tool then uncomment this
# to automatically set up ssh-agent and add the user's key
#SSH_ENV="$HOME/.ssh/environment"
#
#function start_agent {
#     echo "Initialising new SSH agent..."
#     /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
#     echo succeeded
#     chmod 600 "${SSH_ENV}"
#     . "${SSH_ENV}" > /dev/null
#     /usr/bin/ssh-add;
#}
#
## Source SSH settings, if applicable
#
#if [ -f "${SSH_ENV}" ]; then
#     . "${SSH_ENV}" > /dev/null
#     #ps ${SSH_AGENT_PID} doesn't work under cywgin
#     ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
#         start_agent;
#     }
#else
#     start_agent;
#fi
