# bashrc runs for non-login shells, e.g. when you launch gnome-terminal from a desktop

if [ -f /etc/bash_completion ]; then
  source /etc/bash_completion
fi

# Aliases
alias ls="/bin/ls --color=auto"
alias ll="/bin/ls --color=auto -l"
alias la="/bin/ls --color=auto --almost-all"
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias vim=nvim
alias docker-node='docker run --rm -it --volume $PWD:/app --volume $HOME/.npmrc:/root/.npmrc --publish 3000:3000 --workdir /app node'
alias docker-node14='docker run --rm -it --volume $PWD:/app --volume $HOME/.npmrc:/root/.npmrc --publish 3000:3000 --workdir /app node:14'

# Set editors
export VISUAL=vim
export EDITOR=vim

# vi mode
set -o vi

# Set up dircolors to use solarized colors
if [ -x /usr/bin/dircolors ]; then
  test -r ~/.dir_colors/dircolors && eval "$(dircolors -b ~/.dir_colors/dircolors)" || eval "$(dircolors -b)"
fi

# fzf
export FZF_DEFAULT_COMMAND='ag -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
if [ -x ~/.fzf ]; then
    source ~/.fzf/shell/completion.bash
    source ~/.fzf/shell/key-bindings.bash
fi

# Run firefox on wayland
export MOZ_ENABLE_WAYLAND=1

eval $(gnome-keyring-daemon --start)
export SSH_AUTH_SOCK

# android/react-native
export ANDROID_HOME=$HOME/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
