# bashrc runs for non-login shells, e.g. when you launch gnome-terminal from a desktop

# Aliases
alias ls="/bin/ls --color=auto"
alias ll="/bin/ls --color=auto -l"
alias la="/bin/ls --color=auto --almost-all"
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Set editors
export VISUAL=vim
export EDITOR=vim

# vi mode
set -o vi

# Set up dircolors to use solarized colors
if [ -x /usr/bin/dircolors ]; then
  test -r ~/.dir_colors/dircolors && eval "$(dircolors -b ~/.dir_colors/dircolors)" || eval "$(dircolors -b)"
fi

# fzf
export FZF_DEFAULT_COMMAND='ag -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
if [ -x ~/.fzf ]; then
    source ~/.fzf/shell/completion.bash
    source ~/.fzf/shell/key-bindings.bash
fi

# After logging in the agent should not timeout. After all, this is how the
# browser behaves.
export LPASS_AGENT_TIMEOUT=0

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*|tmux*)
    PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD}\007"'
    ;;
*)
    ;;
esac
