#!/bin/bash

meeting_id=$1
if [[ "$meeting_id" =~ ^https.* ]]; then
  meeting_id=$(echo $meeting_id | sed -e 's/https:.*\///')
fi

exec google-chrome-stable \
  --enable-features=WebRTCPipeWireCapturer \
  --enable-features=UseOzonePlatform \
  --ozone-platform=wayland \
  https://zoom.us/wc/join/$meeting_id
