#!/bin/sh

FILE_NAME=$*

TEMP_DIR=$(mktemp -d)
MD_FILE=$(tempfile -d $TEMP_DIR --suffix=.md)

cd $TEMP_DIR

if rclone ls google-drive:"$FILE_NAME" > /dev/null 2>&1; then
    rclone --drive-export-formats docx copy google-drive:"$FILE_NAME" .
    pandoc "$FILE_NAME" -f docx -t gfm -o $MD_FILE
fi


vim $MD_FILE

pandoc $MD_FILE -f gfm -t docx -o $(basename FILE_NAME)

rclone --drive-import-formats docx \
       copyto $(basename FILE_NAME) google-drive:"$FILE_NAME"
