#!/usr/bin/env bash

USAGE="Usage: $0 <namespace> <stage>"

NAMESPACE=$1
CLIENT=${NAMESPACE:$(expr index $NAMESPACE -)}
USER=${NAMESPACE%-$CLIENT}
STAGE=$2
LIMIT_GROUP=${STAGE}-${CLIENT}

if [[ -z "$NAMESPACE" || -z "$STAGE" ]]; then
    echo "$USAGE"
    exit 1
fi

cd ~/esv/repos/build
git pull
./deploy-to-cluster.sh $LIMIT_GROUP configuration/${CLIENT}-config
helm upgrade \
    --install \
    --namespace $NAMESPACE \
    --set image_credentials.password=$(vault read -field=password secret/fni/image-pull) \
    --recreate-pods \
    $NAMESPACE-hdfs energysavvy/hdfs

