#!/usr/bin/env bash

set -o errexit

USAGE="Usage: $0 <namespace>"

if [[ -z "$1" ]]; then
    echo "$USAGE"
    exit 1
fi

NAMESPACE=$1

kubectl delete namespace $NAMESPACE
helm list -q --namespace=$NAMESPACE | while read -r release; do helm delete --purge $release; done 
