#!/usr/bin/env bash

set -o errexit

USAGE="Usage: $0 <namespace> <stage>"

if [[ -z "$1" || -z "$2" ]]; then
    echo "$USAGE"
    exit 1
fi

NAMESPACE=$1
STAGE=$2


CLIENT=${NAMESPACE:$(expr index $NAMESPACE -)}
USER=${NAMESPACE%-$CLIENT}

helm repo update
kubectl create namespace $NAMESPACE || echo 'namespace already exists'
deploy project \
    --stage $STAGE \
    --prefix $USER \
    --client $CLIENT \
    --project ${CLIENT}-config
helm upgrade \
    --install \
    --namespace $NAMESPACE \
    --recreate-pods \
    $NAMESPACE-hdfs energysavvy/hdfs
