#!/usr/bin/env bash

set -o errexit
set -o nounset

NAMESPACE=$1

kubectl delete namespace $NAMESPACE
helm list -q --namespace=$NAMESPACE | while read -r release; do helm delete --purge $release; done 
