#!/usr/bin/env python3
# vim: ft=python

import os
import sys
from os.path import abspath, join, exists, dirname


def main():
    possible_file_arg = sys.argv[-1]
    eslint = 'eslint'
    if exists(join(os.getcwd(), possible_file_arg)):
        try:
            eslint = search_up(
                dirname(possible_file_arg),
                'node_modules/.bin/eslint'
            )
        except FileNotFound as e:
            pass

    os.execvp(eslint, [eslint] + sys.argv[1:])


class FileNotFound(Exception):
    pass


def search_up(directory, relative_path):
    while directory != '/':
        if exists(join(directory, relative_path)):
            return abspath(join(directory, relative_path))
        else:
            directory = abspath(join(directory,  '..'))

    raise FileNotFound(
        'Didn\'t find {} relative to {} or any of it\'s parent directories'
        .format(relative_path, directory)
    )


if __name__ == '__main__':
    main()
