#!/bin/sh

python -m venv .venv && \
  . .venv/bin/activate && \
  pip install --upgrade pip && \
  pip install --upgrade flake8 isort jedi && \
  pip install -r requirements.txt && \
  pip install -r test_requirements.txt
