#!/bin/sh

python3 -m venv .venv && \
  . .venv/bin/activate && \
  pip install --upgrade pip && \
  pip install --upgrade flake8 isort jedi && \
  pip install -r requirements.txt && \
  if [ -f test_requirements.txt ]; then pip install -r test_requirements.txt; fi
