#!/bin/sh

place_window () {
    CMD=$1
    WORKSPACE=$2
    PID=$(ps -e -o pid,cmd | grep "$CMD" | grep -v grep | awk '{print $1}')
    WINDOW=$(wmctrl -l -p | grep $PID | awk '{print $1}')
    wmctrl -i -r $WINDOW -t $WORKSPACE
}

place_window "firefox -p work" 0
place_window "gnome-terminal" 1
place_window "firefox -p communication" 2
place_window "firefox -p personal" 3
