#! /bin/bash
setxkbmap -option ctrl:swapcaps

~/bin/generate_tags.sh &
~/bin/update_repos.sh &

firefox &
hipchat &
gnome-terminal --maximize --working-directory=~/energysavvy --tab --tab --tab --tab &
gnome-terminal --maximize --working-directory=~/energysavvy &
/opt/toggldesktop/TogglDesktop &
