#!/bin/bash

# basic duke vpn
# openconnect portal.duke.edu --user=dfp12 --authgroup=-Default-

# duke health vpn
# { pass show consulting/duke.edu | head -n 1; echo push; } | \
# openconnect vpn.duhs.duke.edu --user=dfp12

# for elevated access
# openconnect dmvpn.duhs.duke.edu --user=dfp12

# force split tunnel
HOSTNAMES=(
  10.96.56.216
  apis-dev.ori.duke.edu
  apis.ori.duke.edu
  app-ingress.dev.platform.dukecrucible.net
  app-ingress.prod.platform.dukecrucible.net
  app-ingress.sandbox.platform.dukecrucible.net
  awsportal.duhs.duke.edu
  crucible-platform-dev-ba6b9d28.hcp.eastus.azmk8s.io
  crucible-platform-prod-7cb2b199.hcp.eastus.azmk8s.io
  dev.fulcrum.duke.edu
  dev.snowball.dukecrucible.net
  devguide.dhe.duke.edu
  exdnc-scan1.dhe.duke.edu
  fulcrum.duke.edu
  gitlab.dhe.duke.edu
  groups.oit.duke.edu
  oauth.oit.duke.edu
  prod.fulcrum.duke.edu
  redcap.duke.edu
  sftp.dev.snowball.dukecrucible.net
  sftp.prod.snowball.dukecrucible.net
  smtp.duhs.duke.edu
  snowball-dev.cluster-cropzucl3dtp.us-east-1.docdb.amazonaws.com
  status.platform.dukecrucible.net
  test.fulcrum.duke.edu
  twistlock-seccon.ocp.dhe.duke.edu
  vld-1kp.dhe.duke.edu
  vld-apisdev01.dhe.duke.edu
  vlt-apistest01.dhe.duke.edu
  vlp-apisprod01.dhe.duke.edu
)
SCRIPT="vpn-slice vla-nc1-nac-app-12.dhe.duke.edu"

function stop_vpn() {
    BLOB=$(grep -oP "#\s+vpn-slice-.*" /etc/hosts | cut -d\# -f2| tail  -n1)
    trap " " SIGTERM SIGINT
    sudo systemctl stop bndaemon.service
    sudo sed --in-place "/$BLOB/d" /etc/hosts
    exit
}

trap 'stop_vpn' SIGINT SIGTERM

sudo systemctl start bndaemon.service
{ pass show consulting/duke.edu | head -n 1; echo push; } | \
sudo openconnect vpn.duhs.duke.edu \
    --background \
    --user=dfp12 \
    --passwd-on-stdin \
    --script="$SCRIPT"

sleep 10
hostify tun0 "${HOSTNAMES[@]}"

while true
do
    sleep 60
done
