#!/usr/bin/env bash

sudo openvpn \
    --config ~/Downloads/energysavvy-openvpn-default-route-dylan.conf \
    --route-gateway dhcp \
    --script-security 2 \
    --up ~/.local/bin/update-systemd-resolved \
    --down ~/.local/bin/update-systemd-resolved \
    --down-pre \
    --daemon
