#!/bin/bash
# From: https://git.sr.ht/~oscarcp/ghostfiles/tree/master/sway_wm/scripts/sway_bar.sh

function print_statusbar() {
    #############
    # Variables
    #############

    # Date and time
    date_and_week=$(date "+%a, %b %d")
    current_time=$(date "+%H:%M")


    #############
    # Commands
    #############

    # Battery or charger
    battery_charge=$(upower --show-info $(upower --enumerate | grep 'BAT') | egrep "percentage" | awk '{print $2}')
    battery_status=$(upower --show-info $(upower --enumerate | grep 'BAT') | egrep "state" | awk '{print $2}')

    # Audio and multimedia
    audio_volume=$(amixer -M get Master | awk '/Mono:.+/ {print $4}' | tr -d [])
    audio_is_muted=$(amixer -M get Master | awk '/Mono:.+/ {print $6=="[off]" ? "true" : "false"}')

    # Network
    network=$(ip route get 1.1.1.1 | grep -Po '(?<=dev\s)\w+' | cut -f1 -d ' ')
    # interface_easyname grabs the "old" interface name before systemd renamed it
    interface_easyname=$(dmesg | grep $network | grep renamed | awk 'NF>1{print $NF}')

    # Others
    loadavg_5min=$(cat /proc/loadavg | awk -F ' ' '{print $2}')

    if [ $battery_status = "discharging" ];
    then
        battery_pluggedin='⚠'
    else
        battery_pluggedin='⚡'
    fi

    if ! [ $network ]
    then
       network_active="⛔"
    else
       network_active="⇆"
    fi

    if [ $audio_is_muted = "true" ]
    then
        audio_active='🔇'
    else
        audio_active='🔊'
    fi


    #############
    # Status Line
    #############

    echo "🕘 $date_and_week $current_time | $audio_active $audio_volume | $battery_pluggedin $battery_charge | $network_active $interface_easyname | 🏋$loadavg_5min |"


    #############
    # Alerts
    #############

    if [ ${battery_charge::-1} -lt 5 ]
    then
        notify-send \
            --urgency=critical \
            "Battery Low!" \
            "Battery below $battery_charge. Computer will suspend soon if not plugged in."
    elif [ ${battery_charge::-1} -lt 3 ]
    then
        notify-send --urgency=critical "Battery Low!" "Suspending..."
        systemctl suspend
    fi
}

trap print_statusbar SIGHUP

while print_statusbar
do
    sleep 30 &
    wait $!
done
