- name: import the nodesource gpg key into apt
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    keyring: /usr/share/keyrings/nodesource.gpg

- name: add nodesource deb repository
  apt_repository:
    repo: 'deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main'
    state: present
    mode: 644

- name: copy apt-preferences
  copy: src=apt-preferences
        dest=/etc/apt/preferences.d/nodejs
        mode='0644'

- name: install nodejs and npm
  apt:
    state: latest
    update_cache: yes
    name:
      - nodejs

- name: install npm packages
  community.general.npm:
    global: yes
    state: latest
    name: '{{ item }}'
  with_items:
    - fixjson
    - jsonlint
    - yarn
