- name: set fonts
  gsetting: schema=org.gnome.desktop.interface
            key={{ item.key }}
            value="'{{ item.value }}'"
  with_items:
    - { key: document-font-name, value: Sans 10 }
    - { key: font-name, value: Ubuntu 10 }
    - { key: monospace-font-name, value: Ubuntu Mono 13 }

- name: set window manager shortcuts
  gsetting: schema=org.gnome.desktop.wm.keybindings
            key={{ item.key }}
            value={{ item.value }}
  with_items:
    - { key: switch-to-workspace-left, value: "['<Control><Alt>h']" }
    - { key: switch-to-workspace-down, value: "['<Control><Alt>j']" }
    - { key: switch-to-workspace-up, value: "['<Control><Alt>k']" }
    - { key: switch-to-workspace-right, value: "['<Control><Alt>l']" }
    - { key: move-to-workspace-left, value: "['<Shift><Control><Alt>h']" }
    - { key: move-to-workspace-down, value: "['<Shift><Control><Alt>j']" }
    - { key: move-to-workspace-up, value: "['<Shift><Control><Alt>k']" }
    - { key: move-to-workspace-right, value: "['<Shift><Control><Alt>l']" }

- name: set lock screeen shortcut
  gsetting: schema=org.gnome.settings-daemon.plugins.media-keys
            key=screensaver
            value="<Super>l"

- name: disable middle click paste
  gsetting: schema=org.gnome.desktop.interface
            key=gtk-enable-primary-paste
            value="false"

- name: make caps lock a ctrl
  gsetting: schema=org.gnome.desktop.input-sources
            key=xkb-options
            value="['ctrl:nocaps']"
