- name: set window manager shortcuts
  gsetting: schema=org.gnome.desktop.wm.keybindings
            key={{ item.key }}
            value={{ item.value }}
  with_items:
    - { key: cycle-windows, value: "['<Alt>h']" }
    - { key: cycle-windows-backward, value: "['<Alt>l']" }
    - { key: toggle-fullscreen, value: "['<Alt>f']" }
    - { key: close, value: "['<Ctrl><Alt>q']" }
    - { key: switch-to-workspace-up, value: "[]" }
    - { key: switch-to-workspace-down, value: "[]" }
    - { key: switch-to-workspace-1, value: "['<Alt>1']" }
    - { key: switch-to-workspace-2, value: "['<Alt>2']" }
    - { key: switch-to-workspace-3, value: "['<Alt>3']" }
    - { key: switch-to-workspace-4, value: "['<Alt>4']" }
    - { key: move-to-workspace-up, value: "[]" }
    - { key: move-to-workspace-down, value: "[]" }
    - { key: move-to-workspace-1, value: "['<Alt><Ctrl>1']" }
    - { key: move-to-workspace-2, value: "['<Alt><Ctrl>2']" }
    - { key: move-to-workspace-3, value: "['<Alt><Ctrl>3']" }
    - { key: move-to-workspace-4, value: "['<Alt><Ctrl>4']" }

- name: set mutter shortcuts
  gsetting: schema=org.gnome.mutter.keybindings
            key={{ item.key }}
            value={{ item.value }}
  with_items:
    - { key: toggle-tiled-left, value: "['<Ctrl><Alt>h']" }
    - { key: toggle-tiled-right, value: "['<Ctrl><Alt>l']" }

- name: set gnome shell shortcuts
  gsetting: schema=org.gnome.shell.keybindings
            key={{ item.key }}
            value={{ item.value }}
  with_items:
    - { key: toggle-overview, value: "['<Alt>apostrophe']" }

- name: set media key shortcuts
  gsetting: schema=org.gnome.settings-daemon.plugins.media-keys
            key={{ item.key }}
            value={{ item.value }}
  with_items:
    - { key: screensaver, value: "['<Super>l']" }
    - { key: screenshot, value: "['<Shift>Print']" }
    - { key: area-screenshot, value: "['Print']" }

- name: disable middle click paste
  gsetting: schema=org.gnome.desktop.interface
            key=gtk-enable-primary-paste
            value="false"

- name: swap alt/ctrl, make caps an escape
  gsetting: schema=org.gnome.desktop.input-sources
            key=xkb-options
            value="['ctrl:swap_lalt_lctl', 'ctrl:swap_ralt_rctl', 'caps:escape']"

- name: set static workspaces
  gsetting: schema=org.gnome.mutter
            key=dynamic-workspaces
            value="false"

- name: configure 4 static workspaces
  gsetting: schema=org.gnome.desktop.wm.preferences
            key=num-workspaces
            value="4"
