- name: set window manager shortcuts
  gsetting: schema=org.gnome.desktop.wm.keybindings
            key={{ item.key }}
            value={{ item.value }}
  with_items:
    - { key: switch-to-workspace-down, value: "['<Alt>j']" }
    - { key: switch-to-workspace-up, value: "['<Alt>k']" }
    - { key: switch-to-workspace-1, value: "['<Alt>1']" }
    - { key: switch-to-workspace-2, value: "['<Alt>2']" }
    - { key: switch-to-workspace-3, value: "['<Alt>3']" }
    - { key: switch-to-workspace-4, value: "['<Alt>4']" }
    - { key: move-to-workspace-down, value: "['<Shift><Alt>j']" }
    - { key: move-to-workspace-up, value: "['<Shift><Alt>k']" }
    - { key: move-to-workspace-1, value: "['<Shift><Alt>1']" }
    - { key: move-to-workspace-2, value: "['<Shift><Alt>2']" }
    - { key: move-to-workspace-3, value: "['<Shift><Alt>3']" }
    - { key: move-to-workspace-4, value: "['<Shift><Alt>4']" }

- name: set lock screeen shortcut
  gsetting: schema=org.gnome.settings-daemon.plugins.media-keys
            key=screensaver
            value="['<Alt>l']"

- name: disable middle click paste
  gsetting: schema=org.gnome.desktop.interface
            key=gtk-enable-primary-paste
            value="false"

- name: insert/update swap_ralt_rctl modifier
  become: yes
  blockinfile:
    path: /usr/share/X11/xkb/symbols/ctrl
    marker: "// {mark} ANSIBLE MANAGED BLOCK"
    block: |
      // Swap the functions of the right Alt key and the right Ctrl key.
      partial modifier_keys
      xkb_symbols "swap_ralt_rctl" {
          replace key <RALT> { [ Control_R, Control_R ] };
          replace key <RCTL> { [ Alt_R, Meta_R ] };
          modifier_map Mod1    { <RCTL> };
          modifier_map Control { <RALT> };
      };

- name: insert/update swap_ralt_rctl description
  become: yes
  blockinfile:
    path: /usr/share/X11/xkb/rules/evdev.lst
    marker: "  // {mark} ANSIBLE MANAGED BLOCK"
    insertafter: ctrl:swap_lalt_lctl.*
    block: "  ctrl:swap_ralt_rctl Swap Right Alt key with Right Ctrl key"

- name: insert/update swap_ralt_rctl option
  become: yes
  blockinfile:
    path: /usr/share/X11/xkb/rules/evdev
    marker: "  // {mark} ANSIBLE MANAGED BLOCK"
    insertafter: ctrl:swap_lalt_lctl.*
    block: "  ctrl:swap_ralt_rctl = +ctrl(swap_ralt_rctl)"

- name: make caps lock a ctrl
  gsetting: schema=org.gnome.desktop.input-sources
            key=xkb-options
            value="['ctrl:swap_lalt_lctl', 'ctrl:swap_ralt_rctl', 'caps:escape']"

- name: set static workspaces
  gsetting: schema=org.gnome.mutter
            key=dynamic-workspaces
            value="false"

- name: configure 4 static workspaces
  gsetting: schema=org.gnome.desktop.wm.preferences
            key=num-workspaces
            value="4"
