- name: install packages
  become: yes
  apt:
    state: latest
    update_cache: yes
    name:
      - geoclue-2.0
      - geoclue-2-demo

- name: create config directories
  file: path={{ ansible_env.HOME }}/{{ item }}
        state=directory
  with_items:
    - .config/systemd/user/

- name: install systemd unit file
  copy: src=geoclue-agent.service 
        dest={{ ansible_env.HOME }}/.config/systemd/user/geoclue-agent.service

- name: configure systemd geoclue
  become: yes
  systemd_service:
    daemon_reload: yes
    name: geoclue.service
    enabled: yes
    state: started

- name: configure systemd geoclue-agent
  systemd_service:
    daemon_reload: yes
    name: geoclue-agent.service
    scope: user
    enabled: yes
    state: started
