- name: fzf | clone repo
  git: repo=https://github.com/junegunn/fzf.git dest={{ ansible_env.HOME }}/.fzf depth=1

- name: fzf | install
  command: '{{ ansible_env.HOME }}/.fzf/install'
  args:
    creates: '{{ ansible_env.HOME }}/.fzf/bin/fzf'

- name: fzf | link into home bin
  file: 
    src: '{{ ansible_env.HOME }}/.fzf/bin/{{ item }}'
    dest: '{{ ansible_env.HOME }}/.local/bin/{{ item }}'
    state: link
  with_items:
    - fzf
    - fzf-tmux
