- name: clone repo
  git: repo=https://github.com/junegunn/fzf.git dest={{ ansible_env.HOME }}/.fzf depth=1

- name: install
  command: '{{ ansible_env.HOME }}/.fzf/install'
  args:
    creates: '{{ ansible_env.HOME }}/.fzf/bin/fzf'

- name: link into home bin
  file: 
    src: '{{ ansible_env.HOME }}/.fzf/bin/fzf'
    dest: '{{ ansible_env.HOME }}/.local/bin/fzf'
    state: link
