- name: insert swap_ralt_rctl modifier
  blockinfile:
    path: /usr/share/X11/xkb/symbols/ctrl
    marker: "// {mark} ANSIBLE MANAGED BLOCK"
    block: |
      // Swap the functions of the right Alt key and the right Ctrl key.
      partial modifier_keys
      xkb_symbols "swap_ralt_rctl" {
          replace key <RALT> { [ Control_R, Control_R ] };
          replace key <RCTL> { [ Alt_R, Meta_R ] };
          modifier_map Mod1    { <RCTL> };
          modifier_map Control { <RALT> };
      };

- name: insert swap_ralt_rctl description
  blockinfile:
    path: /usr/share/X11/xkb/rules/evdev.lst
    marker: "  // {mark} ANSIBLE MANAGED BLOCK"
    insertafter: ctrl:swap_lalt_lctl.*
    block: "  ctrl:swap_ralt_rctl Swap Right Alt key with Right Ctrl key"

- name: insert swap_ralt_rctl option
  blockinfile:
    path: /usr/share/X11/xkb/rules/evdev
    marker: "  // {mark} ANSIBLE MANAGED BLOCK"
    insertafter: ctrl:swap_lalt_lctl.*
    block: "  ctrl:swap_ralt_rctl = +ctrl(swap_ralt_rctl)"
