- name: install
  apt: 
    deb: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2020.03.04_amd64.deb

- name: install systemd unit file
  template: src=dropbox.service dest=/etc/systemd/user/dropbox.service

- name: configure systemd to autostart dropboxd
  systemd:
    name: dropbox.service
    scope: user
    enabled: yes
    state: started
  become: yes
  become_user: '{{ ansible_env.USER }}'
