- name: install jupyter with pipx
  command: pipx install --include-deps jupyter
  args:
    creates: '{{ ansible_env.HOME }}/.local/pipx/venvs/jupyter'

- name: install jupyterlab
  command: pipx inject jupyter jupyterlab --include-apps
  args:
    creates: '{{ ansible_env.HOME }}/.local/pipx/venvs/jupyter/bin/jupyter-lab'

# Plugin not compatible with newest version of jupyterlab.
# - name: install jupyterlab vim extension
#   command: jupyter-labextension install jupyterlab_vim
#   args:
#     creates: '{{ ansible_env.HOME }}/.local/pipx/venvs/jupyter/share/jupyter/lab/extensions/jupyterlab_vim*'
# 
