#!/bin/bash
# Script for installing packages from slackbuild.org
# If you download package.tar.gz, then to install:
# $./install-slackbuild package

PACKAGE="$1"

# Extract package
tar -xzf $PACKAGE.tar.gz
cd $PACKAGE

# Read DOWNLOAD variable
file="$PACKAGE.info"

while read line
do
  if [[ $line == DOWNLOAD_x86_64\=\"http:* ]]
    then
      DOWNLOAD=${line:16}
  fi

done <"$file"

while read line
do
  if [[ $line == DOWNLOAD\=\"http:* ]]
    then
      DOWNLOAD=${line:9}
  fi

done <"$file"

DOWNLOAD=$(echo $DOWNLOAD | tr -d \'\")

wget "$DOWNLOAD"

./$PACKAGE.SlackBuild

cp /tmp/$PACKAGE*.tgz .
installpkg $PACKAGE*.tgz

cd ..
rm -rf $PACKAGE.tar.gz

