- name: download heroku-cli
  unarchive:
    src: https://cli-assets.heroku.com/heroku-linux-x64.tar.xz
    remote_src: yes
    dest: /usr/local/lib
    creates: /usr/local/lib/heroku

- name: install heroku-cli
  file:
    path: /usr/local/bin/heroku
    src: /usr/local/lib/heroku/bin/heroku
    state: link
