- name: import the docker gpg key into apt
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: add docker deb repository
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable'

- name: install docker and docker-compose
  apt: 
    force_apt_get: yes
    state: latest
    update_cache: yes
    name: 
      - docker-ce
      - docker-compose

- name: add docker group
  group: name=docker

- name: add current user to docker group
  user:
    name: '{{ ansible_env.USER }}'
    groups: docker
    append: yes

- name: install docker-credential-secretservice
  unarchive:
    src: https://github.com/docker/docker-credential-helpers/releases/download/v0.6.3/docker-credential-secretservice-v0.6.3-amd64.tar.gz
    remote_src: yes
    dest: /usr/local/bin
    mode: 0555
    creates: /usr/local/bin/docker-credential-secretservice

