- name: copy docker config file
  copy: src=config.json
        dest={{ ansible_env.HOME }}/.docker/config.json
        owner={{ ansible_env.USER }}
        mode=0644

- name: import the docker gpg key into apt
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker.gpg

- name: add docker deb repository
  apt_repository:
    repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable'

- name: install docker
  apt: 
    state: latest
    update_cache: yes
    name: 
      - docker-ce

- name: add docker group
  group: name=docker

- name: add current user to docker group
  user:
    name: '{{ ansible_env.USER }}'
    groups: docker
    append: yes

- name: install docker-credential-secretservice
  get_url:
    url: https://github.com/docker/docker-credential-helpers/releases/download/v0.7.0/docker-credential-secretservice-v0.7.0.linux-amd64
    dest: /usr/local/bin/docker-credential-secretservice
    mode: 0555
