## Docker

- name: import the Docker gpg key into apt
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: add Docker deb repository
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'

- name: install Docker
  apt: name=docker-ce state=latest update_cache=yes

- name: install docker-compose
  apt: name=docker-compose state=latest update_cache=yes

- name: add docker group
  group: name=docker

- name: add current user to docker group
  user:
    name: '{{ ansible_env.USER }}'
    groups: docker
    append: yes
