- name: install packages
  apt:
    state: latest
    name:
      - brightnessctl
      - grim
      - slurp
      - sway
      - swaylock
      - swayidle
      - wl-clipboard

- name: ensures directories exist
  file: path={{ ansible_env.HOME }}/{{ item }} state=directory
  with_items:
    - .local/bin/
    - .config/sway

- name: copy files
  copy: src={{ item.src }}
        dest={{ ansible_env.HOME }}/{{ item.dest }}
        owner={{ ansible_env.USER }}
        mode={{ item.mode | default('0644') }}
  with_items:
    - {src: 'sway-config', dest: '.config/sway/config'}
    - {src: 'sway-launcher', dest: '.local/bin/sway-launcher', mode: '0744'}
    - {src: 'sway-statusbar', dest: '.local/bin/sway-statusbar', mode: '0744'}
