- name: install packages
  become: yes
  apt:
    state: latest
    update_cache: yes
    name:
      - libcairo2-dev
      - libwayland-dev
      - libxkbcommon-dev
      - meson
      - pkg-config
      - wayland-protocols

- name: clone repo
  git: repo=https://github.com/tadeokondrak/waypoint.git
       dest={{ ansible_env.HOME }}/workspace/personal/waypoint
       version=devel
       accept_hostkey=yes

- name: build and install
  become: yes
  ansible.builtin.shell: |
    meson setup build
    meson install -C build
  args:
    chdir: "{{ ansible_env.HOME }}/workspace/personal/waypoint"
    creates: /usr/local/bin/waypoint
