- name: set fonts
  gsetting: schema=org.gnome.desktop.interface
            key={{ item.key }}
            value="'{{ item.value }}'"
  with_items:
    - { key: document-font-name, value: Sans 11 }
    - { key: font-name, value: Ubuntu 11 }
    - { key: monospace-font-name, value: Ubuntu Mono 13 }
